plugins {
    id 'com.android.application'
}

android {
    namespace 'com.fieldintelligence.wp500thermal'
    compileSdk 34

    defaultConfig {
        applicationId 'com.fieldintelligence.wp500thermal'
        minSdk 28
        targetSdk 34
        versionCode 3
        versionName '0.3-radiometric-recorder'
    }
}
